# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import Environment_pb2 as Environment__pb2


class EnvironmentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.handshake_and_validate = channel.unary_unary(
                '/Environment.Environment/handshake_and_validate',
                request_serializer=Environment__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=Environment__pb2.HandshakeResponse.FromString,
                )
        self.sample = channel.unary_unary(
                '/Environment.Environment/sample',
                request_serializer=Environment__pb2.SampleRequest.SerializeToString,
                response_deserializer=Environment__pb2.SampleResponse.FromString,
                )
        self.act = channel.unary_unary(
                '/Environment.Environment/act',
                request_serializer=Environment__pb2.ActionRequest.SerializeToString,
                response_deserializer=Environment__pb2.ActionResponse.FromString,
                )


class EnvironmentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def handshake_and_validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def act(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'handshake_and_validate': grpc.unary_unary_rpc_method_handler(
                    servicer.handshake_and_validate,
                    request_deserializer=Environment__pb2.HandshakeRequest.FromString,
                    response_serializer=Environment__pb2.HandshakeResponse.SerializeToString,
            ),
            'sample': grpc.unary_unary_rpc_method_handler(
                    servicer.sample,
                    request_deserializer=Environment__pb2.SampleRequest.FromString,
                    response_serializer=Environment__pb2.SampleResponse.SerializeToString,
            ),
            'act': grpc.unary_unary_rpc_method_handler(
                    servicer.act,
                    request_deserializer=Environment__pb2.ActionRequest.FromString,
                    response_serializer=Environment__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Environment.Environment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Environment(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def handshake_and_validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Environment.Environment/handshake_and_validate',
            Environment__pb2.HandshakeRequest.SerializeToString,
            Environment__pb2.HandshakeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Environment.Environment/sample',
            Environment__pb2.SampleRequest.SerializeToString,
            Environment__pb2.SampleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def act(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Environment.Environment/act',
            Environment__pb2.ActionRequest.SerializeToString,
            Environment__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
