# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Environment.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x45nvironment.proto\x12\x0b\x45nvironment\"\x12\n\x04ICCE\x12\n\n\x02id\x18\x01 \x01(\x05\"*\n\x07\x45nvData\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07\x65pisode\x18\x02 \x01(\x05\x32\x46\n\x0b\x45nvironment\x12\x37\n\nGetEnvData\x12\x11.Environment.ICCE\x1a\x14.Environment.EnvData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Environment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ICCE']._serialized_start=34
  _globals['_ICCE']._serialized_end=52
  _globals['_ENVDATA']._serialized_start=54
  _globals['_ENVDATA']._serialized_end=96
  _globals['_ENVIRONMENT']._serialized_start=98
  _globals['_ENVIRONMENT']._serialized_end=168
# @@protoc_insertion_point(module_scope)
