# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Environment.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x45nvironment.proto\x12\x0b\x45nvironment\"=\n\x10HandshakeRequest\x12\x16\n\x0en_observations\x18\x01 \x01(\x05\x12\x11\n\tn_actions\x18\x02 \x01(\x05\"/\n\x11HandshakeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x05\"\x1a\n\x0cStartRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"C\n\rStartResponse\x12\"\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x14.Environment.EnvData\x12\x0e\n\x06status\x18\x02 \x01(\x05\"\x1c\n\x0e\x45nvDataRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"E\n\x0f\x45nvDataResponse\x12\"\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x14.Environment.EnvData\x12\x0e\n\x06status\x18\x02 \x01(\x05\"\x1b\n\rActionRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x0e\x41\x63tionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"g\n\x07\x45nvData\x12\x14\n\x0cobservations\x18\x01 \x01(\x0c\x12\x0e\n\x06reward\x18\x02 \x01(\x02\x12\x12\n\nterminated\x18\x03 \x01(\x08\x12\x11\n\ttruncated\x18\x04 \x01(\x08\x12\x0f\n\x07\x65pisode\x18\x05 \x01(\x05\x32\xd0\x02\n\x0b\x45nvironment\x12Y\n\x16handshake_and_validate\x12\x1d.Environment.HandshakeRequest\x1a\x1e.Environment.HandshakeResponse\"\x00\x12K\n\x10start_simulation\x12\x19.Environment.StartRequest\x1a\x1a.Environment.StartResponse\"\x00\x12K\n\x0cget_env_data\x12\x1b.Environment.EnvDataRequest\x1a\x1c.Environment.EnvDataResponse\"\x00\x12L\n\x0fset_action_data\x12\x1a.Environment.ActionRequest\x1a\x1b.Environment.ActionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Environment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HANDSHAKEREQUEST']._serialized_start=34
  _globals['_HANDSHAKEREQUEST']._serialized_end=95
  _globals['_HANDSHAKERESPONSE']._serialized_start=97
  _globals['_HANDSHAKERESPONSE']._serialized_end=144
  _globals['_STARTREQUEST']._serialized_start=146
  _globals['_STARTREQUEST']._serialized_end=172
  _globals['_STARTRESPONSE']._serialized_start=174
  _globals['_STARTRESPONSE']._serialized_end=241
  _globals['_ENVDATAREQUEST']._serialized_start=243
  _globals['_ENVDATAREQUEST']._serialized_end=271
  _globals['_ENVDATARESPONSE']._serialized_start=273
  _globals['_ENVDATARESPONSE']._serialized_end=342
  _globals['_ACTIONREQUEST']._serialized_start=344
  _globals['_ACTIONREQUEST']._serialized_end=371
  _globals['_ACTIONRESPONSE']._serialized_start=373
  _globals['_ACTIONRESPONSE']._serialized_end=405
  _globals['_ENVDATA']._serialized_start=407
  _globals['_ENVDATA']._serialized_end=510
  _globals['_ENVIRONMENT']._serialized_start=513
  _globals['_ENVIRONMENT']._serialized_end=849
# @@protoc_insertion_point(module_scope)
